package com.mxh.weibo.common.model;

import java.util.ArrayList;
import java.util.List;

public class FollowFollowerExample {
    /**
	 * @mbggenerated
	 */
	protected String orderByClause;
	/**
	 * @mbggenerated
	 */
	protected boolean distinct;
	/**
	 * @mbggenerated
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method corresponds to the database table weibo_follow_follower
	 * @mbggenerated
	 */
	public FollowFollowerExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method corresponds to the database table weibo_follow_follower
	 * @mbggenerated
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method corresponds to the database table weibo_follow_follower
	 * @mbggenerated
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method corresponds to the database table weibo_follow_follower
	 * @mbggenerated
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method corresponds to the database table weibo_follow_follower
	 * @mbggenerated
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method corresponds to the database table weibo_follow_follower
	 * @mbggenerated
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method corresponds to the database table weibo_follow_follower
	 * @mbggenerated
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method corresponds to the database table weibo_follow_follower
	 * @mbggenerated
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method corresponds to the database table weibo_follow_follower
	 * @mbggenerated
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method corresponds to the database table weibo_follow_follower
	 * @mbggenerated
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method corresponds to the database table weibo_follow_follower
	 * @mbggenerated
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table weibo_follow_follower
	 * @mbggenerated
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("followFollower.ID is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("followFollower.ID is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("followFollower.ID =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("followFollower.ID <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("followFollower.ID >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("followFollower.ID >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("followFollower.ID <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("followFollower.ID <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Integer> values) {
			addCriterion("followFollower.ID in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Integer> values) {
			addCriterion("followFollower.ID not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("followFollower.ID between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("followFollower.ID not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andFollowIsNull() {
			addCriterion("followFollower.FOLLOW is null");
			return (Criteria) this;
		}

		public Criteria andFollowIsNotNull() {
			addCriterion("followFollower.FOLLOW is not null");
			return (Criteria) this;
		}

		public Criteria andFollowEqualTo(String value) {
			addCriterion("followFollower.FOLLOW =", value, "follow");
			return (Criteria) this;
		}

		public Criteria andFollowNotEqualTo(String value) {
			addCriterion("followFollower.FOLLOW <>", value, "follow");
			return (Criteria) this;
		}

		public Criteria andFollowGreaterThan(String value) {
			addCriterion("followFollower.FOLLOW >", value, "follow");
			return (Criteria) this;
		}

		public Criteria andFollowGreaterThanOrEqualTo(String value) {
			addCriterion("followFollower.FOLLOW >=", value, "follow");
			return (Criteria) this;
		}

		public Criteria andFollowLessThan(String value) {
			addCriterion("followFollower.FOLLOW <", value, "follow");
			return (Criteria) this;
		}

		public Criteria andFollowLessThanOrEqualTo(String value) {
			addCriterion("followFollower.FOLLOW <=", value, "follow");
			return (Criteria) this;
		}

		public Criteria andFollowLike(String value) {
			addCriterion("followFollower.FOLLOW like", value, "follow");
			return (Criteria) this;
		}

		public Criteria andFollowNotLike(String value) {
			addCriterion("followFollower.FOLLOW not like", value, "follow");
			return (Criteria) this;
		}

		public Criteria andFollowIn(List<String> values) {
			addCriterion("followFollower.FOLLOW in", values, "follow");
			return (Criteria) this;
		}

		public Criteria andFollowNotIn(List<String> values) {
			addCriterion("followFollower.FOLLOW not in", values, "follow");
			return (Criteria) this;
		}

		public Criteria andFollowBetween(String value1, String value2) {
			addCriterion("followFollower.FOLLOW between", value1, value2, "follow");
			return (Criteria) this;
		}

		public Criteria andFollowNotBetween(String value1, String value2) {
			addCriterion("followFollower.FOLLOW not between", value1, value2, "follow");
			return (Criteria) this;
		}

		public Criteria andFollowedIsNull() {
			addCriterion("followFollower.FOLLOWED is null");
			return (Criteria) this;
		}

		public Criteria andFollowedIsNotNull() {
			addCriterion("followFollower.FOLLOWED is not null");
			return (Criteria) this;
		}

		public Criteria andFollowedEqualTo(String value) {
			addCriterion("followFollower.FOLLOWED =", value, "followed");
			return (Criteria) this;
		}

		public Criteria andFollowedNotEqualTo(String value) {
			addCriterion("followFollower.FOLLOWED <>", value, "followed");
			return (Criteria) this;
		}

		public Criteria andFollowedGreaterThan(String value) {
			addCriterion("followFollower.FOLLOWED >", value, "followed");
			return (Criteria) this;
		}

		public Criteria andFollowedGreaterThanOrEqualTo(String value) {
			addCriterion("followFollower.FOLLOWED >=", value, "followed");
			return (Criteria) this;
		}

		public Criteria andFollowedLessThan(String value) {
			addCriterion("followFollower.FOLLOWED <", value, "followed");
			return (Criteria) this;
		}

		public Criteria andFollowedLessThanOrEqualTo(String value) {
			addCriterion("followFollower.FOLLOWED <=", value, "followed");
			return (Criteria) this;
		}

		public Criteria andFollowedLike(String value) {
			addCriterion("followFollower.FOLLOWED like", value, "followed");
			return (Criteria) this;
		}

		public Criteria andFollowedNotLike(String value) {
			addCriterion("followFollower.FOLLOWED not like", value, "followed");
			return (Criteria) this;
		}

		public Criteria andFollowedIn(List<String> values) {
			addCriterion("followFollower.FOLLOWED in", values, "followed");
			return (Criteria) this;
		}

		public Criteria andFollowedNotIn(List<String> values) {
			addCriterion("followFollower.FOLLOWED not in", values, "followed");
			return (Criteria) this;
		}

		public Criteria andFollowedBetween(String value1, String value2) {
			addCriterion("followFollower.FOLLOWED between", value1, value2, "followed");
			return (Criteria) this;
		}

		public Criteria andFollowedNotBetween(String value1, String value2) {
			addCriterion("followFollower.FOLLOWED not between", value1, value2, "followed");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table weibo_follow_follower
	 * @mbggenerated
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class corresponds to the database table weibo_follow_follower
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}