package com.mxh.weibo.common.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class WeiboExample {
    /**
	 * @mbggenerated
	 */
	protected String orderByClause;
	/**
	 * @mbggenerated
	 */
	protected boolean distinct;
	/**
	 * @mbggenerated
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method corresponds to the database table weibo_weibo
	 * @mbggenerated
	 */
	public WeiboExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method corresponds to the database table weibo_weibo
	 * @mbggenerated
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method corresponds to the database table weibo_weibo
	 * @mbggenerated
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method corresponds to the database table weibo_weibo
	 * @mbggenerated
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method corresponds to the database table weibo_weibo
	 * @mbggenerated
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method corresponds to the database table weibo_weibo
	 * @mbggenerated
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method corresponds to the database table weibo_weibo
	 * @mbggenerated
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method corresponds to the database table weibo_weibo
	 * @mbggenerated
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method corresponds to the database table weibo_weibo
	 * @mbggenerated
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method corresponds to the database table weibo_weibo
	 * @mbggenerated
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method corresponds to the database table weibo_weibo
	 * @mbggenerated
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table weibo_weibo
	 * @mbggenerated
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andUuidIsNull() {
			addCriterion("weibo.UUID is null");
			return (Criteria) this;
		}

		public Criteria andUuidIsNotNull() {
			addCriterion("weibo.UUID is not null");
			return (Criteria) this;
		}

		public Criteria andUuidEqualTo(String value) {
			addCriterion("weibo.UUID =", value, "uuid");
			return (Criteria) this;
		}

		public Criteria andUuidNotEqualTo(String value) {
			addCriterion("weibo.UUID <>", value, "uuid");
			return (Criteria) this;
		}

		public Criteria andUuidGreaterThan(String value) {
			addCriterion("weibo.UUID >", value, "uuid");
			return (Criteria) this;
		}

		public Criteria andUuidGreaterThanOrEqualTo(String value) {
			addCriterion("weibo.UUID >=", value, "uuid");
			return (Criteria) this;
		}

		public Criteria andUuidLessThan(String value) {
			addCriterion("weibo.UUID <", value, "uuid");
			return (Criteria) this;
		}

		public Criteria andUuidLessThanOrEqualTo(String value) {
			addCriterion("weibo.UUID <=", value, "uuid");
			return (Criteria) this;
		}

		public Criteria andUuidLike(String value) {
			addCriterion("weibo.UUID like", value, "uuid");
			return (Criteria) this;
		}

		public Criteria andUuidNotLike(String value) {
			addCriterion("weibo.UUID not like", value, "uuid");
			return (Criteria) this;
		}

		public Criteria andUuidIn(List<String> values) {
			addCriterion("weibo.UUID in", values, "uuid");
			return (Criteria) this;
		}

		public Criteria andUuidNotIn(List<String> values) {
			addCriterion("weibo.UUID not in", values, "uuid");
			return (Criteria) this;
		}

		public Criteria andUuidBetween(String value1, String value2) {
			addCriterion("weibo.UUID between", value1, value2, "uuid");
			return (Criteria) this;
		}

		public Criteria andUuidNotBetween(String value1, String value2) {
			addCriterion("weibo.UUID not between", value1, value2, "uuid");
			return (Criteria) this;
		}

		public Criteria andUserIdIsNull() {
			addCriterion("weibo.USER_ID is null");
			return (Criteria) this;
		}

		public Criteria andUserIdIsNotNull() {
			addCriterion("weibo.USER_ID is not null");
			return (Criteria) this;
		}

		public Criteria andUserIdEqualTo(String value) {
			addCriterion("weibo.USER_ID =", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotEqualTo(String value) {
			addCriterion("weibo.USER_ID <>", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdGreaterThan(String value) {
			addCriterion("weibo.USER_ID >", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdGreaterThanOrEqualTo(String value) {
			addCriterion("weibo.USER_ID >=", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdLessThan(String value) {
			addCriterion("weibo.USER_ID <", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdLessThanOrEqualTo(String value) {
			addCriterion("weibo.USER_ID <=", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdLike(String value) {
			addCriterion("weibo.USER_ID like", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotLike(String value) {
			addCriterion("weibo.USER_ID not like", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdIn(List<String> values) {
			addCriterion("weibo.USER_ID in", values, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotIn(List<String> values) {
			addCriterion("weibo.USER_ID not in", values, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdBetween(String value1, String value2) {
			addCriterion("weibo.USER_ID between", value1, value2, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotBetween(String value1, String value2) {
			addCriterion("weibo.USER_ID not between", value1, value2, "userId");
			return (Criteria) this;
		}

		public Criteria andPublishTimeIsNull() {
			addCriterion("weibo.PUBLISH_TIME is null");
			return (Criteria) this;
		}

		public Criteria andPublishTimeIsNotNull() {
			addCriterion("weibo.PUBLISH_TIME is not null");
			return (Criteria) this;
		}

		public Criteria andPublishTimeEqualTo(Date value) {
			addCriterion("weibo.PUBLISH_TIME =", value, "publishTime");
			return (Criteria) this;
		}

		public Criteria andPublishTimeNotEqualTo(Date value) {
			addCriterion("weibo.PUBLISH_TIME <>", value, "publishTime");
			return (Criteria) this;
		}

		public Criteria andPublishTimeGreaterThan(Date value) {
			addCriterion("weibo.PUBLISH_TIME >", value, "publishTime");
			return (Criteria) this;
		}

		public Criteria andPublishTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("weibo.PUBLISH_TIME >=", value, "publishTime");
			return (Criteria) this;
		}

		public Criteria andPublishTimeLessThan(Date value) {
			addCriterion("weibo.PUBLISH_TIME <", value, "publishTime");
			return (Criteria) this;
		}

		public Criteria andPublishTimeLessThanOrEqualTo(Date value) {
			addCriterion("weibo.PUBLISH_TIME <=", value, "publishTime");
			return (Criteria) this;
		}

		public Criteria andPublishTimeIn(List<Date> values) {
			addCriterion("weibo.PUBLISH_TIME in", values, "publishTime");
			return (Criteria) this;
		}

		public Criteria andPublishTimeNotIn(List<Date> values) {
			addCriterion("weibo.PUBLISH_TIME not in", values, "publishTime");
			return (Criteria) this;
		}

		public Criteria andPublishTimeBetween(Date value1, Date value2) {
			addCriterion("weibo.PUBLISH_TIME between", value1, value2, "publishTime");
			return (Criteria) this;
		}

		public Criteria andPublishTimeNotBetween(Date value1, Date value2) {
			addCriterion("weibo.PUBLISH_TIME not between", value1, value2, "publishTime");
			return (Criteria) this;
		}

		public Criteria andContentIsNull() {
			addCriterion("weibo.CONTENT is null");
			return (Criteria) this;
		}

		public Criteria andContentIsNotNull() {
			addCriterion("weibo.CONTENT is not null");
			return (Criteria) this;
		}

		public Criteria andContentEqualTo(String value) {
			addCriterion("weibo.CONTENT =", value, "content");
			return (Criteria) this;
		}

		public Criteria andContentNotEqualTo(String value) {
			addCriterion("weibo.CONTENT <>", value, "content");
			return (Criteria) this;
		}

		public Criteria andContentGreaterThan(String value) {
			addCriterion("weibo.CONTENT >", value, "content");
			return (Criteria) this;
		}

		public Criteria andContentGreaterThanOrEqualTo(String value) {
			addCriterion("weibo.CONTENT >=", value, "content");
			return (Criteria) this;
		}

		public Criteria andContentLessThan(String value) {
			addCriterion("weibo.CONTENT <", value, "content");
			return (Criteria) this;
		}

		public Criteria andContentLessThanOrEqualTo(String value) {
			addCriterion("weibo.CONTENT <=", value, "content");
			return (Criteria) this;
		}

		public Criteria andContentLike(String value) {
			addCriterion("weibo.CONTENT like", value, "content");
			return (Criteria) this;
		}

		public Criteria andContentNotLike(String value) {
			addCriterion("weibo.CONTENT not like", value, "content");
			return (Criteria) this;
		}

		public Criteria andContentIn(List<String> values) {
			addCriterion("weibo.CONTENT in", values, "content");
			return (Criteria) this;
		}

		public Criteria andContentNotIn(List<String> values) {
			addCriterion("weibo.CONTENT not in", values, "content");
			return (Criteria) this;
		}

		public Criteria andContentBetween(String value1, String value2) {
			addCriterion("weibo.CONTENT between", value1, value2, "content");
			return (Criteria) this;
		}

		public Criteria andContentNotBetween(String value1, String value2) {
			addCriterion("weibo.CONTENT not between", value1, value2, "content");
			return (Criteria) this;
		}

		public Criteria andPraiseIsNull() {
			addCriterion("weibo.PRAISE is null");
			return (Criteria) this;
		}

		public Criteria andPraiseIsNotNull() {
			addCriterion("weibo.PRAISE is not null");
			return (Criteria) this;
		}

		public Criteria andPraiseEqualTo(Integer value) {
			addCriterion("weibo.PRAISE =", value, "praise");
			return (Criteria) this;
		}

		public Criteria andPraiseNotEqualTo(Integer value) {
			addCriterion("weibo.PRAISE <>", value, "praise");
			return (Criteria) this;
		}

		public Criteria andPraiseGreaterThan(Integer value) {
			addCriterion("weibo.PRAISE >", value, "praise");
			return (Criteria) this;
		}

		public Criteria andPraiseGreaterThanOrEqualTo(Integer value) {
			addCriterion("weibo.PRAISE >=", value, "praise");
			return (Criteria) this;
		}

		public Criteria andPraiseLessThan(Integer value) {
			addCriterion("weibo.PRAISE <", value, "praise");
			return (Criteria) this;
		}

		public Criteria andPraiseLessThanOrEqualTo(Integer value) {
			addCriterion("weibo.PRAISE <=", value, "praise");
			return (Criteria) this;
		}

		public Criteria andPraiseIn(List<Integer> values) {
			addCriterion("weibo.PRAISE in", values, "praise");
			return (Criteria) this;
		}

		public Criteria andPraiseNotIn(List<Integer> values) {
			addCriterion("weibo.PRAISE not in", values, "praise");
			return (Criteria) this;
		}

		public Criteria andPraiseBetween(Integer value1, Integer value2) {
			addCriterion("weibo.PRAISE between", value1, value2, "praise");
			return (Criteria) this;
		}

		public Criteria andPraiseNotBetween(Integer value1, Integer value2) {
			addCriterion("weibo.PRAISE not between", value1, value2, "praise");
			return (Criteria) this;
		}

		public Criteria andLikedIsNull() {
			addCriterion("weibo.LIKED is null");
			return (Criteria) this;
		}

		public Criteria andLikedIsNotNull() {
			addCriterion("weibo.LIKED is not null");
			return (Criteria) this;
		}

		public Criteria andLikedEqualTo(Integer value) {
			addCriterion("weibo.LIKED =", value, "liked");
			return (Criteria) this;
		}

		public Criteria andLikedNotEqualTo(Integer value) {
			addCriterion("weibo.LIKED <>", value, "liked");
			return (Criteria) this;
		}

		public Criteria andLikedGreaterThan(Integer value) {
			addCriterion("weibo.LIKED >", value, "liked");
			return (Criteria) this;
		}

		public Criteria andLikedGreaterThanOrEqualTo(Integer value) {
			addCriterion("weibo.LIKED >=", value, "liked");
			return (Criteria) this;
		}

		public Criteria andLikedLessThan(Integer value) {
			addCriterion("weibo.LIKED <", value, "liked");
			return (Criteria) this;
		}

		public Criteria andLikedLessThanOrEqualTo(Integer value) {
			addCriterion("weibo.LIKED <=", value, "liked");
			return (Criteria) this;
		}

		public Criteria andLikedIn(List<Integer> values) {
			addCriterion("weibo.LIKED in", values, "liked");
			return (Criteria) this;
		}

		public Criteria andLikedNotIn(List<Integer> values) {
			addCriterion("weibo.LIKED not in", values, "liked");
			return (Criteria) this;
		}

		public Criteria andLikedBetween(Integer value1, Integer value2) {
			addCriterion("weibo.LIKED between", value1, value2, "liked");
			return (Criteria) this;
		}

		public Criteria andLikedNotBetween(Integer value1, Integer value2) {
			addCriterion("weibo.LIKED not between", value1, value2, "liked");
			return (Criteria) this;
		}

		public Criteria andDeletedIsNull() {
			addCriterion("weibo.DELETED is null");
			return (Criteria) this;
		}

		public Criteria andDeletedIsNotNull() {
			addCriterion("weibo.DELETED is not null");
			return (Criteria) this;
		}

		public Criteria andDeletedEqualTo(Byte value) {
			addCriterion("weibo.DELETED =", value, "deleted");
			return (Criteria) this;
		}

		public Criteria andDeletedNotEqualTo(Byte value) {
			addCriterion("weibo.DELETED <>", value, "deleted");
			return (Criteria) this;
		}

		public Criteria andDeletedGreaterThan(Byte value) {
			addCriterion("weibo.DELETED >", value, "deleted");
			return (Criteria) this;
		}

		public Criteria andDeletedGreaterThanOrEqualTo(Byte value) {
			addCriterion("weibo.DELETED >=", value, "deleted");
			return (Criteria) this;
		}

		public Criteria andDeletedLessThan(Byte value) {
			addCriterion("weibo.DELETED <", value, "deleted");
			return (Criteria) this;
		}

		public Criteria andDeletedLessThanOrEqualTo(Byte value) {
			addCriterion("weibo.DELETED <=", value, "deleted");
			return (Criteria) this;
		}

		public Criteria andDeletedIn(List<Byte> values) {
			addCriterion("weibo.DELETED in", values, "deleted");
			return (Criteria) this;
		}

		public Criteria andDeletedNotIn(List<Byte> values) {
			addCriterion("weibo.DELETED not in", values, "deleted");
			return (Criteria) this;
		}

		public Criteria andDeletedBetween(Byte value1, Byte value2) {
			addCriterion("weibo.DELETED between", value1, value2, "deleted");
			return (Criteria) this;
		}

		public Criteria andDeletedNotBetween(Byte value1, Byte value2) {
			addCriterion("weibo.DELETED not between", value1, value2, "deleted");
			return (Criteria) this;
		}

		public Criteria andReplyNumIsNull() {
			addCriterion("weibo.REPLY_NUM is null");
			return (Criteria) this;
		}

		public Criteria andReplyNumIsNotNull() {
			addCriterion("weibo.REPLY_NUM is not null");
			return (Criteria) this;
		}

		public Criteria andReplyNumEqualTo(Integer value) {
			addCriterion("weibo.REPLY_NUM =", value, "replyNum");
			return (Criteria) this;
		}

		public Criteria andReplyNumNotEqualTo(Integer value) {
			addCriterion("weibo.REPLY_NUM <>", value, "replyNum");
			return (Criteria) this;
		}

		public Criteria andReplyNumGreaterThan(Integer value) {
			addCriterion("weibo.REPLY_NUM >", value, "replyNum");
			return (Criteria) this;
		}

		public Criteria andReplyNumGreaterThanOrEqualTo(Integer value) {
			addCriterion("weibo.REPLY_NUM >=", value, "replyNum");
			return (Criteria) this;
		}

		public Criteria andReplyNumLessThan(Integer value) {
			addCriterion("weibo.REPLY_NUM <", value, "replyNum");
			return (Criteria) this;
		}

		public Criteria andReplyNumLessThanOrEqualTo(Integer value) {
			addCriterion("weibo.REPLY_NUM <=", value, "replyNum");
			return (Criteria) this;
		}

		public Criteria andReplyNumIn(List<Integer> values) {
			addCriterion("weibo.REPLY_NUM in", values, "replyNum");
			return (Criteria) this;
		}

		public Criteria andReplyNumNotIn(List<Integer> values) {
			addCriterion("weibo.REPLY_NUM not in", values, "replyNum");
			return (Criteria) this;
		}

		public Criteria andReplyNumBetween(Integer value1, Integer value2) {
			addCriterion("weibo.REPLY_NUM between", value1, value2, "replyNum");
			return (Criteria) this;
		}

		public Criteria andReplyNumNotBetween(Integer value1, Integer value2) {
			addCriterion("weibo.REPLY_NUM not between", value1, value2, "replyNum");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table weibo_weibo
	 * @mbggenerated
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class corresponds to the database table weibo_weibo
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}